app/src/main/java/de/stephanlindauer/criticalmaps/service/LocationUpdatesService.java
app/src/main/java/de/stephanlindauer/criticalmaps/service/ServerSyncService.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/ApplicationCloser.java

Hey,
I know this is your WIP/dirty branch. But as you're releasing from it I I thought I'd still submit. If this is more confusing than helping, let me know ;)

various lifecycle related stuff 

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java

There is no sensitive data in there ( all public anyway ) - so we can add this to prevent the need for unlocking the phone

Show Main Activity when locked.

---

app/src/main/res/layout/activity_splashscreen.xml
app/src/main/res/layout/fragment_about.xml
app/src/main/res/layout/fragment_chat.xml
app/src/main/res/layout/fragment_map.xml
app/src/main/res/layout/fragment_rules.xml
app/src/main/res/layout/fragment_twitter.xml
app/src/main/res/layout/view_chatmessage.xml
app/src/main/res/layout/view_introduction.xml
app/src/main/res/layout/view_outgoing_chatmessage.xml
app/src/main/res/layout/view_picture_upload.xml
app/src/main/res/layout/view_searching_for_location_overlay.xml
app/src/main/res/layout/view_tweet.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/styles.xml

I introduced [design time layout attributes](http://tools.android.com/tips/layout-designtime-attributes) in a few places to make it easier to understand the layouts.

Cleanup layout files

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/notifications/trackinginfo/TrackingInfoNotificationSetter.java
app/src/main/java/de/stephanlindauer/criticalmaps/service/LocationUpdatesService.java

Let's not keep references to an activity in objects that can outlive the activity itself.

Fix memory leaks

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java

missed that in the previous commit

fix memory leak

---

app/src/main/java/de/stephanlindauer/criticalmaps/handler/PullServerHandler.java

Use android logging in PullServerHandler

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/adapter/TabsPagerAdapter.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/helper/clientinfo/DeviceInformation.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/TrackingInfoNotificationBuilder.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/menu/actionbar_buttons.xml

This mainly handles deprecated code (minor changes), but also switches to AppCompatActivity with a TabLayout. This adds a hint of material design of the app and could be the base for further "materialization". Any thoughts and opinions?

Handle deprecations and slight ui update

---

app/build.gradle
build.gradle

My previous PR failed to build on travis as SDK 23 was not there - sdkmanager plugin to the rescue ;-)

Add sdkmanager

---

app/src/main/java/de/stephanlindauer/criticalmaps/handler/ApplicationCloseHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/PrerequisitesChecker.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/ProcessCameraResultHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/StartCameraHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/AlertBuilder.java

+some removing of unused imports / indentation

Use support-v7 AlertDialog

---

app/src/main/res/layout/fragment_about.xml
app/src/main/res/layout/fragment_rules.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values/donottranslate.xml
app/src/main/res/values/strings.xml

Sorry for the last commit, was to lazy to rebase it in :dancers: 
After a merge it would be great if @canerbasaran and @rodrigoaguilera could update the corresponding translations.

Make hardcoded strings resources and update turkish and spanish xmls

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/RulesFragment.java

first one should be straightforward.
reagrding the second one: To me it feels "wrong" not to be able to close the panels again - especially since the button still animates.

rules fragment

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/MapViewUtils.java
app/src/main/res/layout/view_searching_for_location_overlay.xml

First step in cleaning up the mapview and gps handling.
I will probably push some more commits tonight in a separate pull request.

Mapfragment cleanup

---

.gitignore

No, I don't want to commit my heapdumps.

add captures to gitignore

---

README.md

Based on @johnjohndoe 's PR with screenshot from media repo

Add ScreenShot from media repo

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/ChatModel.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/OtherUsersLocationModel.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/OwnLocationModel.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/SternfahrtModel.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/TwitterModel.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/UserModel.java
app/src/main/java/de/stephanlindauer/criticalmaps/provider/EventBusProvider.java
app/src/main/java/de/stephanlindauer/criticalmaps/service/LocationUpdatesService.java

singletons will be singletons + misc cleanup
oh and I accidentaly pushed another commit that should have been on another branch, but it's good to go

Singletons

---

app/src/main/java/de/stephanlindauer/criticalmaps/model/SternfahrtModel.java

otherwise UI thread will get blocked

spin off sternfahrt route generation to another thread

---

app/src/main/AndroidManifest.xml
app/src/main/java/de/stephanlindauer/criticalmaps/handler/ApplicationCloseHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/AlertBuilder.java
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Most of this is preparation for further materialization - more to come....
This also changes the colors a bit, I tried to compromise between what we have and the material guidelines here. Screenshot of what it looks like on API 22:

Styles and themes

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/AboutFragment.java
app/src/main/res/layout/fragment_about.xml
app/src/main/res/layout/fragment_chat.xml
app/src/main/res/layout/fragment_map.xml
app/src/main/res/layout/fragment_rules.xml
app/src/main/res/layout/fragment_twitter.xml
app/src/main/res/layout/view_chatmessage.xml
app/src/main/res/layout/view_introduction.xml
app/src/main/res/layout/view_outgoing_chatmessage.xml
app/src/main/res/layout/view_picture_upload.xml
app/src/main/res/values/styles.xml

tested on API 16 and 22 emulators and on 19 device

layouts cleanup

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/AboutFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/RulesFragment.java
app/src/main/res/layout/fragment_about.xml
app/src/main/res/layout/fragment_map.xml
app/src/main/res/layout/fragment_rules.xml

Save fragment states

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/DrawerClosingDrawerLayoutListener.java

Opening the Drawer closes the Keyboard

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/res/layout/fragment_map.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

required to comply with openstreetmaps licensing
see: http://www.openstreetmap.org/copyright
I tried my best to balance legibility with blending it into the background. Doesn't seem to intrusive to me.

add osm copyright notice

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/PullServerHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/OwnLocationModel.java
app/src/main/java/de/stephanlindauer/criticalmaps/service/LocationUpdatesService.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/ApplicationCloser.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/LocationUtils.java

- also use network provider
- filter new locations by quality before using them
- only submit "precise" locations to server
- some cleanup and refactoring
All the parameters used to filter the location and the definition of what we consider precise should be okay for a start. I'd appreciate it if you could take a look and do a quick test yourselves to verify and maybe correct me ;)
replaces #112 to use new target branch

Improve location handling

---

app/src/main/res/layout/activity_main.xml
app/src/main/res/values/colors.xml

continuation of https://github.com/criticalmaps/criticalmaps-android/pull/121

Transparent side drawer

---

gradle/wrapper/gradle-wrapper.properties

This can improve speed of builds

Use Gradle 2.8

---

app/src/main/java/de/stephanlindauer/criticalmaps/handler/PullServerHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/OwnLocationModel.java
app/src/main/java/de/stephanlindauer/criticalmaps/service/LocationUpdatesService.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/DateUtils.java

don't send old location fixes to backend

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/AboutFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/views/LicensePanelView.java
app/src/main/res/layout/fragment_about.xml
app/src/main/res/layout/license_panel_view.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/licenses.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

add license info for third party libraries to about

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/RulesFragment.java
app/src/main/res/layout/fragment_rules.xml

suppresses the fade in animation of the image

don't show rules panel animation on state restore

---

app/src/main/java/de/stephanlindauer/criticalmaps/handler/PullServerHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/UserModel.java

added salt to uniqueDeviceId

---

app/src/main/java/de/stephanlindauer/criticalmaps/App.java
app/src/main/java/de/stephanlindauer/criticalmaps/AppComponent.java
app/src/main/java/de/stephanlindauer/criticalmaps/AppModule.java
app/src/main/java/de/stephanlindauer/criticalmaps/adapter/TweetAdapter.java

... and let Dagger manage the picasso singleton

use existing okhttpclient for picasso

---

app/src/main/java/de/stephanlindauer/criticalmaps/handler/PullServerHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/ServerResponseProcessor.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/TwitterGetHandler.java

sorry for the indescript title - see the commit messages :)

Misc changes

---

app/src/main/java/de/stephanlindauer/criticalmaps/AppComponent.java
app/src/main/java/de/stephanlindauer/criticalmaps/AppModule.java
app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/managers/LocationUpdateManager.java
app/src/main/java/de/stephanlindauer/criticalmaps/service/ServerSyncService.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/ApplicationCloser.java

see commit message
renaming to manager is equally generic, but it's clearly not a service

Start stop location updates in service

---

app/src/main/java/de/stephanlindauer/criticalmaps/managers/LocationUpdateManager.java

Fix npe in locationmanager

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/ChatFragment.java
app/src/main/res/animator/chat_fab_state_change.xml
app/src/main/res/color/chat_fab_background_states.xml
app/src/main/res/color/chat_fab_drawable_states.xml
app/src/main/res/layout/fragment_chat.xml

The automagic hide/fade/layoutchange animation seemed a bit clunky to me. With this change the sendbutton is always visible but greyed out/disabled until text is entered. The state changes are animated similar to hangouts.
Input is appreciated. :)

Rework chat send button

---

app/build.gradle
app/src/main/java/de/stephanlindauer/criticalmaps/App.java
app/src/main/java/de/stephanlindauer/criticalmaps/AppComponent.java
app/src/main/java/de/stephanlindauer/criticalmaps/AppModule.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/PrerequisitesChecker.java
app/src/main/java/de/stephanlindauer/criticalmaps/managers/LocationUpdateManager.java
app/src/main/java/de/stephanlindauer/criticalmaps/prefs/GeoPointPreference.java
app/src/main/java/de/stephanlindauer/criticalmaps/prefs/SharedPrefsKeys.java
app/src/main/java/de/stephanlindauer/criticalmaps/vo/SharedPrefsKeys.java
app/src/main/res/layout/fragment_about.xml
app/src/main/res/values/licenses.xml

+ Inject shared preferences.
+ Please note that former setting will NOT be restored since
preferences keys change in this commit. See SharedPrefKeys.java.

Simplify usage of shared preferences.

---

app/src/main/res/values-ca/strings.xml
app/src/main/res/values-es/strings.xml

PR to develop instead of master
https://github.com/criticalmaps/criticalmaps-android/pull/160

Add Catalan translation and update Spanish.

---

.gitignore
.travis.yml
app/build.gradle
app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/TwitterFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/overlays/LocationMarker.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/MapViewUtils.java
app/src/main/res/layout/fragment_chat.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Just some minor updates
@ligi I just stole the first commit from your current PR

Housekeeping

---

app/build.gradle
app/lint.xml
app/src/main/java/de/stephanlindauer/criticalmaps/adapter/TweetAdapter.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/UserModel.java
app/src/main/res/drawable/ic_content_add.xml
app/src/main/res/layout/fragment_chat.xml
app/src/main/res/layout/fragment_map.xml
app/src/main/res/layout/fragment_twitter.xml
app/src/main/res/layout/view_searching_for_location_overlay.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values/strings.xml

...and fix color of new tweet icon

fix appcompat vector drawables

---

app/src/main/res/values-de/strings.xml

second commit only adds the strings to simplify updating the translations later

Translations

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java

https://github.com/criticalmaps/criticalmaps-android/blob/905c15516881ee46a550184f52e337c16fa9b43c/app/src/main/java/de/stephanlindauer/criticalmaps/Main.java#L134

Datenschutz URL outdated / non-existent

---

app/src/main/java/de/stephanlindauer/criticalmaps/vo/Endpoints.java

i want to make this a patch-version, which is why i am pointing this PR straight to master.

Use old endpoints again

---

app/build.gradle
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/helper/clientinfo/DeviceInformation.java
app/src/main/java/de/stephanlindauer/criticalmaps/managers/LocationUpdateManager.java
app/src/main/java/de/stephanlindauer/criticalmaps/service/ServerSyncService.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/MapViewUtils.java
app/src/main/res/animator/map_gps_fab_searching_animation.xml
app/src/main/res/drawable/ic_gps_not_fixed_white_24dp.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_chat.xml
app/src/main/res/layout/fragment_map.xml
app/src/main/res/layout/fragment_twitter.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-tr/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
build.gradle

1) Some cleanup and lib updates - no major changes here
2) Map
**Initial Map Location and Searching for Location State:**
**OnClick Message:**
**Animation changes alpha of fab to make it "pulsate":**

Housekeeping and gps waiting state

---

app/src/main/java/de/stephanlindauer/criticalmaps/App.java
app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/managers/LocationUpdateManager.java

Fixes two possible crashes connected to relaunching the app after quitting it.

Service fix

---

app/build.gradle
app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/events/GpsStatusChangedEvent.java
app/src/main/java/de/stephanlindauer/criticalmaps/events/NetworkConnectivityChangedEvent.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/PermissionCheckHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/StartCameraHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/managers/LocationUpdateManager.java
app/src/main/java/de/stephanlindauer/criticalmaps/model/PermissionRequest.java
app/src/main/res/values/strings.xml

Adds basic infrastructure for requesting permissions and handling state
and uses it for the existing permissions.
This is definitely not the cleanest solution and I'm not perfectly happy with it, but I think we should get this in to move forward.
It would be great if you could give this a thorough test. Also suggestions regarding the wording are welcome.

Add runtime permissions

---

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java

Save map orientation state

---

app/build.gradle
app/src/androidTest/java/de/stephanlindauer/criticalmaps/ApplicationTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/SettingsFragment.java
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
build.gradle

Regarding jcenter:
https://twitter.com/JakeWharton/status/1073102730443526144

Lib updates + get rid of jcenter + ui test setup

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/AboutFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/res/drawable/toolbar_background.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_about.xml
app/src/main/res/layout/fragment_chat.xml
app/src/main/res/layout/fragment_map.xml
app/src/main/res/layout/fragment_rules.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/fragment_twitter.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/styles.xml

- smaller toolbar in mapview
- transparent toolbar in mapview on api => 21
- animations between map and other fragments

Make map more immersive

---

app/src/main/res/values-it/strings.xml

Fix italian translation mistake

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/StartCameraHandler.java

Save file as URI and save/restore it on device rotation

Fix crash while taking picture and rotating device

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/SettingsFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/prefs/SharedPrefsKeys.java
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values-ca/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings.xml

Screen options

---

.travis.yml

they have supplied very little value so far so lets get rid of them
@criticalmaps/android

Discontinue Slack build notifications

---

.github/CODEOWNERS

https://help.github.com/en/articles/about-code-owners

Use github codeowners

---

app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/navdrawer_observer_mode_switch.xml
app/src/main/res/menu/menu_navdrawer.xml

Hide observer mode for release

---

app/build.gradle
app/src/main/java/de/stephanlindauer/criticalmaps/App.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/SettingsFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/helper/clientinfo/DeviceInformation.java
app/src/main/java/de/stephanlindauer/criticalmaps/prefs/SharedPrefsKeys.java
app/src/main/java/de/stephanlindauer/criticalmaps/provider/StorageLocationProvider.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/MapViewUtils.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/TrackingInfoNotificationBuilder.java
app/src/main/res/drawable/logo.xml
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/values/strings.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

workaround until #249 is fixed. default is on.

Make rotation optional

---

app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/navdrawer_observer_mode_switch.xml
app/src/main/res/menu/menu_navdrawer.xml

This reverts commit 30c0202718f35075fcf016e3c05e88fad40179cc.

Revert "Hide observer mode for release"

---

app/src/main/res/values-fr/strings.xml
app/src/main/res/values/strings-notranslate.xml

Thanks to @AlbanSagouis for updating the translations! :)

Update french translations from transifex

---

app/src/main/res/values-tr/strings.xml

Update turkish translations

---

app/src/main/res/values-ja/strings.xml
app/src/main/res/values-ru/strings.xml

/cc @cbalster 
FYI @CptMaister
Closes https://github.com/criticalmaps/criticalmaps-android/issues/268 & https://github.com/criticalmaps/criticalmaps-android/issues/267

Added Russian & Japanese locales

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java

Hi,
If you don't mind, accept my PR with closing navigation drawer, when an user clicks on Back button. I think it's useful for all users, because in whole apps closing drawer is default behaviour, e.g Gmail, Google play, etc.

Close nav drawer when Back button was pressed

---

app/build.gradle
app/src/main/java/de/stephanlindauer/criticalmaps/adapter/TweetAdapter.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/TwitterFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/TimeToWordStringConverter.java
app/src/main/java/de/stephanlindauer/criticalmaps/views/CircleTransformation.java
app/src/main/res/drawable/twitter_avatar_placeholder.xml
app/src/main/res/layout/fragment_twitter.xml
app/src/main/res/layout/view_tweet.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
build.gradle

Closes https://github.com/criticalmaps/criticalmaps-android/issues/252
**Changes**:
1. "Add tweet" button will be hide while scrolling down
2. Added ripple effect on the Tweet item
3. ProgressBar placeholder is replaced by gray (#ccc) circle
@cbalster @stephanlindauer @zutrinken

Twitter new design

---

app/src/main/AndroidManifest.xml

Fix broken chat layout

---

app/build.gradle
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/TwitterFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/utils/MapViewUtils.java
app/src/main/res/layout/view_observer_infowindow.xml
app/src/main/res/layout/view_tweet.xml
build.gradle

Fix twitter layout and bump dependencies

---

app/src/main/res/color/navigation_drawer_item_background_states.xml
app/src/main/res/drawable-hdpi/nav_drawer_item_background_states.xml
app/src/main/res/layout/activity_main.xml

For some reason this worked fine before when pushing via adb, but failed with a built apk...

Fix drawer background

---

app/build.gradle
app/src/main/java/de/stephanlindauer/criticalmaps/Main.java
app/src/main/java/de/stephanlindauer/criticalmaps/adapter/ChatMessageAdapter.java
app/src/main/java/de/stephanlindauer/criticalmaps/adapter/TweetAdapter.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/AboutFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/ChatFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/SettingsFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/fragments/TwitterFragment.java
app/src/main/java/de/stephanlindauer/criticalmaps/handler/TwitterGetHandler.java
app/src/main/java/de/stephanlindauer/criticalmaps/views/LicensePanelView.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/fragment_about.xml
app/src/main/res/layout/fragment_chat.xml
app/src/main/res/layout/fragment_map.xml
app/src/main/res/layout/fragment_rules.xml
app/src/main/res/layout/fragment_settings.xml
app/src/main/res/layout/fragment_twitter.xml
app/src/main/res/layout/license_panel_view.xml
app/src/main/res/layout/navdrawer_header.xml
app/src/main/res/layout/navdrawer_observer_mode_switch.xml
app/src/main/res/layout/view_chatmessage.xml
app/src/main/res/layout/view_license_panel.xml
app/src/main/res/layout/view_observer_infowindow.xml
app/src/main/res/layout/view_picture_upload.xml
app/src/main/res/layout/view_tweet.xml

butterknife is deprecated and recommends migration.

Migrate to view binding

---

.travis.yml

Update travis to API29

---

app/src/main/java/de/stephanlindauer/criticalmaps/Main.java

Return to map on back navigation
