app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java, app/src/main/java/de/stephanlindauer/criticalmaps/overlays/LocationMarker.java
The Marker class holds a static reference to a DefaultInfoWindow instance
which in turn holds a reference to the MapView. Thus it leaks the entire
view hierarchy when the fragment is detached.
Work around this by sub classing marker and implementing Overlay's
onDetach() method to null out the static references there.
Also move common initialization code to the subclass.
=> Fix memory leak due to osmbonuspack bug

app/src/main/java/de/stephanlindauer/criticalmaps/service/ServerSyncService.java
AsyncTasks must be started from the UI thread and as of JELLYBEAN this is automatically taken care of.
Since we're running it from a TimerTask - which is a separate thread - we have to take care of this ourselves
for devices running ICS and lower.
fixes #42
=> fix crash on ICS

.travis.yml, app/build.gradle, app/src/main/java/de/stephanlindauer/criticalmaps/handler/PullServerHandler.java, app/src/main/java/de/stephanlindauer/criticalmaps/handler/TwitterGetHandler.java, app/src/main/java/de/stephanlindauer/criticalmaps/provider/EventBusProvider.java, app/src/main/java/de/stephanlindauer/criticalmaps/provider/HttpClientProvider.java
OKHttp is a good replacement do handle the deprecations that come with SDK23 - also shortens the code here - could even have some other benefits - from the website: 
```
HTTP is the way modern applications network. It’s how we exchange data & media. Doing HTTP efficiently makes your stuff load faster and saves bandwidth.
OkHttp is an HTTP client that’s efficient by default:
HTTP/2 and SPDY support allows all requests to the same host to share a socket.
Connection pooling reduces request latency (if SPDY isn’t available).
Transparent GZIP shrinks download sizes.
Response caching avoids the network completely for repeat requests.
OkHttp perseveres when the network is troublesome: it will silently recover from common connection problems. If your service has multiple IP addresses OkHttp will …
```
=> Migrate to okhttp

app/src/main/res/layout/fragment_rules.xml, app/src/main/res/values/styles.xml
currently the text around the link is white on white
btw. we should probably think about making the color definitions more general and not view specific to avoid redundandcy.
=> Fix text color in rules image source

app/src/main/java/de/stephanlindauer/criticalmaps/service/LocationUpdatesService.java
So it is done in the background and we get rid of one more warning
=> Replace commit with apply

app/src/main/java/de/stephanlindauer/criticalmaps/handler/TwitterGetHandler.java
when we navigate away from the twitter fragment while
an asynctask is still running it will triger an update to
views which have already been destroyed and thus
causes a NPE.
check if the fragment is added before trying to update it
fixes #92
=> fix NPE on twitter fragment

app/src/main/res/layout/view_tweet.xml, app/src/main/res/values/dimens.xml
I took a look at the view hierarchy of the app. I found the layout for the **tweet layout** too complex. So I refactored this.
@ligi @cbalster @stephanlindauer
Please run this on your devices (also tablets) to check if tweets still layout fine.
I also added the needed attributes to prepare the view for right-to-left mode.
=> Tweet layout

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/TwitterFragment.java, app/src/main/res/drawable-nodpi/border_bottom.xml, app/src/main/res/drawable-nodpi/border_top.xml, app/src/main/res/layout/fragment_twitter.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/styles.xml
I think we have some cleanup to do regarding the different colors used in the app, especially when moving to a more material design. So firstly this reduces the number of colors by trying to replace them by a few common ones. Secondly this moves all color definitions to the colors.xml to have them in a common place.
Obviously this changes the appearance of the app a bit. Something that proved a bit problematic is that our current primary primary dark color is really close to the default Theme.Appcompat window background. Especially I'm not too happy with the background of the chat edittext (even though I think it'll just do for now). Therefore I added it to the colors and style, to prepare a change here.
So this should be seen as a first step to get things organized and moving to a …
=> Color cleanup

app/src/main/java/de/stephanlindauer/criticalmaps/adapter/TweetAdapter.java, app/src/main/res/layout/view_tweet.xml
Otherwise the progress-bar still consumes CPU-Cycles and will make problems with espresso-testing
=> Remove the tweet user-image loading progress-bar after loading

app/src/main/java/de/stephanlindauer/criticalmaps/handler/PullServerHandler.java
quote from docs: "To facilitate connection recycling, callers should always close the response body."
=> close response body after use

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/ChatFragment.java, app/src/main/res/layout/fragment_chat.xml
As we agreed the overlay is not the most visually appealing way to indicate we're still waiting for a location fix. Let's get rid of it by disabling the EditText and showing a message in the hint text instead. I think the state change should be made more obvious for example by adding an animation, but one step at a time ;)
=> Chat location state handling

.travis.yml
I activated travis CI for slack and added the notification configuration to the travis file. Now we can get notifications in android channel on slack after each build. I already implemented this in the ios project and really liked it!
=> Add slack notifications to travis configuration

app/src/main/java/de/stephanlindauer/criticalmaps/handler/ImageUploadHandler.java
even though this works we should use publishProgress()
to ensure proper synchronization
=> ImageUploadHandler: fix progress update

app/src/main/java/de/stephanlindauer/criticalmaps/adapter/ChatMessageAdapter.java, app/src/main/java/de/stephanlindauer/criticalmaps/adapter/TweetAdapter.java, app/src/main/java/de/stephanlindauer/criticalmaps/managers/LocationUpdateManager.java, app/src/main/java/de/stephanlindauer/criticalmaps/model/ChatModel.java, app/src/main/java/de/stephanlindauer/criticalmaps/model/OwnLocationModel.java, app/src/main/java/de/stephanlindauer/criticalmaps/model/TwitterModel.java, app/src/main/java/de/stephanlindauer/criticalmaps/views/LicensePanelView.java
This pull request is focused on resolving occurrences of Sonar rules
squid:S1319 - Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList".
squid:S1213 - The members of an interface declaration or class should appear in a pre-defined order. 
squid:UselessParenthesesCheck - Useless parentheses around expressions should be removed to prevent any misunderstanding.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1319
https://dev.eclipse.org/sonar/rules/show/squid:S1213
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck
Please let me know if you have any questions.
George Kankava
=> Multiple code improvements - squid:S1319, squid:S1213, squid:UselessParenthesesCheck

app/src/main/java/de/stephanlindauer/criticalmaps/utils/DateUtils.java, app/src/main/java/de/stephanlindauer/criticalmaps/utils/ImageUtils.java, app/src/main/java/de/stephanlindauer/criticalmaps/utils/IntentUtil.java, app/src/main/java/de/stephanlindauer/criticalmaps/utils/LocationUtils.java, app/src/main/java/de/stephanlindauer/criticalmaps/utils/MapViewUtils.java, app/src/main/java/de/stephanlindauer/criticalmaps/utils/TwitterUtils.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1118 - Utility classes should not have public constructors.
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1118
Please let me know if you have any questions.
George Kankava
=> squid:S1118 - Utility classes should not have public constructors

app/build.gradle, app/src/main/java/de/stephanlindauer/criticalmaps/service/ServerSyncService.java, app/src/main/java/de/stephanlindauer/criticalmaps/utils/MapViewUtils.java
Individual paths returned by getExternalFilesDirs() can be null when
they are unavailable. Handle that case by skipping the location.
=> Fix crash while discovering storage location and workaround service issues in O

app/src/main/java/de/stephanlindauer/criticalmaps/fragments/ChatFragment.java
@cbalster @stephanlindauer 
1) I think we should disable 'Send message' button if trimmed message is empty. Now an user can send empty or started with white spaces message. It looks like a spam.
2) An unused private variable removed
=> Disable 'Send' button if message is empty

app/src/main/java/de/stephanlindauer/criticalmaps/adapter/TweetAdapter.java
Not sure why it linked to Aasiv Mandvis account. :laughing: 
Even with the wrong user handle it always displayed the correct tweet in the end. :confused:
=> fix wrong twitter handle linkage

app/src/test/java/de/stephanlindauer/criticalmaps/model/OwnLocationModelTest.java
- This resolves the TODO `use JUnit's assertThrows() instead when 4.13 is out`.
---
_Feel free to rebase this branch onto the latest commit of `master` to facilitate a linear history. Let me know if I should do it._
=> Use Assert#assertThrows.

app/src/main/res/layout/fragment_rules.xml
Some people on the CM have gotten into trouble for alleged "Nötigung". Let's disable this rule until we know more.
It's a weird development considering that the cops were previously always very thankful when cyclists helped them cork the streets.
=> Disable corking rule

.aiexclude, .github/workflows/android.yml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/de/stephanlindauer/criticalmaps/AppComponent.java, app/src/main/java/de/stephanlindauer/criticalmaps/Main.java, app/src/main/java/de/stephanlindauer/criticalmaps/adapter/ChatMessageAdapter.java, app/src/main/java/de/stephanlindauer/criticalmaps/fragments/ChatFragment.java, app/src/main/java/de/stephanlindauer/criticalmaps/fragments/MapFragment.java, app/src/main/java/de/stephanlindauer/criticalmaps/handler/PermissionCheckHandler.java, app/src/main/java/de/stephanlindauer/criticalmaps/managers/LocationUpdateManager.java, app/src/main/java/de/stephanlindauer/criticalmaps/model/ChatModel.java, app/src/main/java/de/stephanlindauer/criticalmaps/model/OtherUsersLocationModel.java, app/src/main/java/de/stephanlindauer/criticalmaps/service/ServerSyncService.java, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values/strings.xml, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties
We need to urgently update to API 35, so the app will remain available on play store.
At the same time we had some issues on newer API Versions not showing the service
notification. This lead to people leaving tracking on unintentionally. This has been fixed.
To simplify permission handling, we handle location and notification access together.
=> Fix Notification and update targetSdk
